CREATE DATABASE messenger;

CREATE TABLE users(
    id SERIAL PRIMARY KEY,
    username VARCHAR(28) NOT NULL UNIQUE,
    passhash VARCHAR NOT NULL,
    userid VARCHAR NOT NULL UNIQUE -- this is generated by uuid at login so socketio knows who to send messages to
);

-- INSERT INTO users(username, passhash) values($1,$2);